"""Render the captured application catalogue; never connects to a database."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
c = json.loads((ROOT / 'catalog.json').read_text())
def qi(s): return '"' + s.replace('"', '""') + '"'
def lit(s): return "'" + s.replace("'", "''") + "'"
def obj(x): return qi(x['schema']) + '.' + qi(x.get('table', x.get('name')))
out = ['-- GENERATED by generate.py from catalog.json. Do not edit by hand.',
       '-- Empty, disposable Supabase-compatible target ONLY. Not a production migration.',
       '-- Known authorization gaps are intentionally preserved.', 'BEGIN;',
       "SET LOCAL search_path = public, pg_catalog;",
       "DO $guard$ BEGIN\n  IF current_setting('ting.baseline_replay', true) IS DISTINCT FROM 'approved-empty-target' THEN\n    RAISE EXCEPTION 'Set ting.baseline_replay=approved-empty-target on a disposable target only';\n  END IF;\n  IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('public','ting_private') AND c.relkind IN ('r','p','v','m','S')) THEN\n    RAISE EXCEPTION 'Refusing nonempty application schemas';\n  END IF;\n  IF to_regclass('auth.users') IS NULL OR to_regclass('storage.objects') IS NULL OR to_regclass('storage.buckets') IS NULL THEN\n    RAISE EXCEPTION 'Supabase managed auth/storage prerequisites missing';\n  END IF;\nEND $guard$;",
       'CREATE SCHEMA IF NOT EXISTS ting_private AUTHORIZATION postgres;']
for t in c['tables']:
    cols = []
    for a in t['columns']:
        assert not a['identity'] and not a['generated'], 'Unsupported generated/identity column'
        s = qi(a['name']) + ' ' + a['type']
        if a['default'] is not None: s += ' DEFAULT ' + a['default']
        if a['not_null']: s += ' NOT NULL'
        cols.append(s)
    out += ['CREATE TABLE ' + obj(t) + ' (\n  ' + ',\n  '.join(cols) + '\n);',
            'ALTER TABLE ' + obj(t) + ' OWNER TO ' + qi(t['owner']) + ';']
    if t['comment'] is not None: out.append('COMMENT ON TABLE '+obj(t)+' IS '+lit(t['comment'])+';')
    for a in t['columns']:
        if a['comment'] is not None: out.append('COMMENT ON COLUMN '+obj(t)+'.'+qi(a['name'])+' IS '+lit(a['comment'])+';')
for k in sorted(c['constraints'], key=lambda k: k['type']=='f'):
    out.append('ALTER TABLE '+obj(k)+' ADD CONSTRAINT '+qi(k['name'])+' '+k['definition']+';')
for i in c['indexes']:
    if not i['constraint_backed']: out.append(i['definition']+';')
for f in c['functions']:
    out += [f['definition'].rstrip().rstrip(';')+';', 'ALTER FUNCTION '+obj(f)+'('+f['identity_args']+') OWNER TO '+qi(f['owner'])+';']
for t in c['triggers']:
    out.append(t['definition']+';')
    state={'O':'ENABLE', 'D':'DISABLE', 'R':'ENABLE REPLICA', 'A':'ENABLE ALWAYS'}[t['enabled']]
    out.append('ALTER TABLE '+obj(t)+' '+state+' TRIGGER '+qi(t['name'])+';')
for p in c['policies']:
    roles = ', '.join('PUBLIC' if r=='public' else qi(r) for r in p['roles'])
    s='CREATE POLICY '+qi(p['policyname'])+' ON '+qi(p['schemaname'])+'.'+qi(p['tablename'])+' AS '+p['permissive']+' FOR '+p['cmd']+' TO '+roles
    if p['qual'] is not None: s+=' USING ('+p['qual']+')'
    if p['with_check'] is not None: s+=' WITH CHECK ('+p['with_check']+')'
    out.append(s+';')
for t in c['tables']:
    out.append('ALTER TABLE '+obj(t)+(' ENABLE' if t['rls'] else ' DISABLE')+' ROW LEVEL SECURITY;')
    out.append('ALTER TABLE '+obj(t)+(' FORCE' if t['force_rls'] else ' NO FORCE')+' ROW LEVEL SECURITY;')
    assert t['replica_identity'] in ('d','f','n')
    out.append('ALTER TABLE '+obj(t)+' REPLICA IDENTITY '+{'d':'DEFAULT','f':'FULL','n':'NOTHING'}[t['replica_identity']]+';')

privs={'a':'INSERT','r':'SELECT','w':'UPDATE','d':'DELETE','D':'TRUNCATE','x':'REFERENCES','t':'TRIGGER','m':'MAINTAIN','X':'EXECUTE','U':'USAGE','C':'CREATE'}
def grants(acl, kind, target, prefix=''):
    assert acl is not None, 'Null ACL requires explicit default handling'
    parsed=[]
    for item in acl:
        who, tail=item.split('=',1)
        perms, grantor=tail.split('/',1)
        assert '"' not in who and '*' not in perms, 'Unsupported ACL shape'
        parsed.append((who,perms))
    roles=sorted(set(['','anon','authenticated','service_role']+[x[0] for x in parsed]))
    role=lambda s: qi(s) if s else 'PUBLIC'
    out.append(prefix+'REVOKE ALL ON '+kind+' '+target+' FROM '+', '.join(role(r) for r in roles)+';')
    for who, perms in parsed:
        out.append(prefix+'GRANT '+', '.join(privs[p] for p in perms)+' ON '+kind+' '+target+' TO '+role(who)+';')
for s in c['schemas']:
    out.append('ALTER SCHEMA '+qi(s['name'])+' OWNER TO '+qi(s['owner'])+';')
    grants(s['acl'],'SCHEMA',qi(s['name']))
for t in c['tables']: grants(t['acl'],'TABLE',obj(t))
for f in c['functions']: grants(f['acl'],'FUNCTION',obj(f)+'('+f['identity_args']+')')
# Default ACLs are captured separately: platform-owned supabase_admin defaults
# must not be altered by an application restore. Recreate postgres defaults only.
for d in c['default_acls']:
    if d['owner']!='postgres': continue
    scope=' IN SCHEMA '+qi(d['schema']) if d['schema'] else ''
    prefix='ALTER DEFAULT PRIVILEGES FOR ROLE '+qi(d['owner'])+scope+' '
    grants(d['acl'],{'r':'TABLES','f':'FUNCTIONS','S':'SEQUENCES'}[d['type']],'',prefix)
for p in c['publications']:
    assert not p['all_tables']
    ops=', '.join(k for k in ['insert','update','delete','truncate'] if p[k])
    out += ["DO $pub$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname="+lit(p['name'])+") THEN EXECUTE 'CREATE PUBLICATION "+qi(p['name'])+"'; END IF; END $pub$;",
            'ALTER PUBLICATION '+qi(p['name'])+' SET (publish = '+lit(ops)+', publish_via_partition_root = '+str(p['via_root']).lower()+');',
            'ALTER PUBLICATION '+qi(p['name'])+' OWNER TO '+qi(p['owner'])+';']
    for t in c['publication_tables']:
        if t['pubname']==p['name']:
            assert t.get('rowfilter') is None
            out.append('ALTER PUBLICATION '+qi(p['name'])+' ADD TABLE '+qi(t['schemaname'])+'.'+qi(t['tablename'])+';')
for b in c['buckets']:
    mime='NULL' if b['allowed_mime_types'] is None else 'ARRAY['+', '.join(lit(x) for x in b['allowed_mime_types'])+']::text[]'
    size='NULL' if b['file_size_limit'] is None else str(b['file_size_limit'])
    out.append('INSERT INTO storage.buckets (id,name,public,file_size_limit,allowed_mime_types) VALUES ('+','.join([lit(b['id']),lit(b['name']),str(b['public']).lower(),size,mime])+');')
for e in c['event_triggers']:
    tags=' WHEN TAG IN ('+', '.join(lit(t) for t in e['tags'])+')' if e['tags'] else ''
    out.append('CREATE EVENT TRIGGER '+qi(e['name'])+' ON '+e['event']+tags+' EXECUTE FUNCTION '+e['function']+'();')
    out.append('ALTER EVENT TRIGGER '+qi(e['name'])+' OWNER TO '+qi(e['owner'])+';')
    out.append('ALTER EVENT TRIGGER '+qi(e['name'])+' '+{'O':'ENABLE','D':'DISABLE','R':'ENABLE REPLICA','A':'ENABLE ALWAYS'}[e['enabled']]+';')
out.append('COMMIT;')
(ROOT/'schema.sql').write_text('\n\n'.join(out)+'\n')
print('Generated schema.sql:',len(out),'statements/sections')
