-- GENERATED by generate.py from catalog.json. Do not edit by hand.

-- Empty, disposable Supabase-compatible target ONLY. Not a production migration.

-- Known authorization gaps are intentionally preserved.

BEGIN;

SET LOCAL search_path = public, pg_catalog;

DO $guard$ BEGIN
  IF current_setting('ting.baseline_replay', true) IS DISTINCT FROM 'approved-empty-target' THEN
    RAISE EXCEPTION 'Set ting.baseline_replay=approved-empty-target on a disposable target only';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('public','ting_private') AND c.relkind IN ('r','p','v','m','S')) THEN
    RAISE EXCEPTION 'Refusing nonempty application schemas';
  END IF;
  IF to_regclass('auth.users') IS NULL OR to_regclass('storage.objects') IS NULL OR to_regclass('storage.buckets') IS NULL THEN
    RAISE EXCEPTION 'Supabase managed auth/storage prerequisites missing';
  END IF;
END $guard$;

CREATE SCHEMA IF NOT EXISTS ting_private AUTHORIZATION postgres;

CREATE TABLE "public"."admin_users" (
  "user_id" uuid NOT NULL,
  "created_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE "public"."admin_users" OWNER TO "postgres";

CREATE TABLE "public"."menu_events" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "event_type" text NOT NULL,
  "item_id" uuid,
  "table_number" text,
  "client_slug" text NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb,
  "created_at" timestamp with time zone DEFAULT now(),
  "tenant_id" uuid
);

ALTER TABLE "public"."menu_events" OWNER TO "postgres";

CREATE TABLE "public"."menu_items" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "client_slug" text NOT NULL,
  "name" text NOT NULL,
  "price" numeric NOT NULL,
  "description" text,
  "image_url" text,
  "tags" text[] DEFAULT '{}'::text[],
  "is_out_of_stock" boolean DEFAULT false,
  "is_promo" boolean DEFAULT false,
  "promo_price" numeric,
  "sort_order" integer DEFAULT 0,
  "created_at" timestamp with time zone DEFAULT now(),
  "tenant_id" uuid
);

ALTER TABLE "public"."menu_items" OWNER TO "postgres";

CREATE TABLE "public"."restaurant_clients" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "client_slug" text NOT NULL,
  "supabase_url" text NOT NULL,
  "supabase_anon_key" text NOT NULL,
  "restaurant_name" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE "public"."restaurant_clients" OWNER TO "postgres";

CREATE TABLE "public"."restaurant_settings" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "restaurant_name" text,
  "google_place_id" text,
  "accent_color" text DEFAULT '#e67e22'::text,
  "logo_url" text,
  "created_at" timestamp with time zone DEFAULT now(),
  "tenant_id" uuid
);

ALTER TABLE "public"."restaurant_settings" OWNER TO "postgres";

CREATE TABLE "public"."service_tickets" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "table_number" text NOT NULL,
  "request_type" text NOT NULL,
  "status" text DEFAULT 'pending'::text,
  "created_at" timestamp with time zone DEFAULT now(),
  "tenant_id" uuid NOT NULL,
  "client_slug" text
);

ALTER TABLE "public"."service_tickets" OWNER TO "postgres";

CREATE TABLE "public"."table_configurations" (
  "source_table" text NOT NULL,
  "target_table" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "tenant_id" uuid
);

ALTER TABLE "public"."table_configurations" OWNER TO "postgres";

CREATE TABLE "public"."tenant_memberships" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "role" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."tenant_memberships" OWNER TO "postgres";

CREATE TABLE "public"."tenants" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "client_slug" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."tenants" OWNER TO "postgres";

ALTER TABLE "public"."menu_events" ADD CONSTRAINT "menu_events_client_slug_clean" CHECK (client_slug ~ '^[A-Za-z0-9_-]{1,80}$'::text);

ALTER TABLE "public"."menu_events" ADD CONSTRAINT "menu_events_known_event_type" CHECK (event_type = ANY (ARRAY['menu_view'::text, 'item_viewed'::text, 'filter_used'::text, 'assistance_requested'::text]));

ALTER TABLE "public"."menu_events" ADD CONSTRAINT "menu_events_metadata_object" CHECK (metadata IS NULL OR jsonb_typeof(metadata) = 'object'::text);

ALTER TABLE "public"."menu_items" ADD CONSTRAINT "menu_items_price_nonnegative" CHECK (price >= 0::numeric);

ALTER TABLE "public"."menu_items" ADD CONSTRAINT "menu_items_promo_price_nonnegative" CHECK (promo_price IS NULL OR promo_price >= 0::numeric);

ALTER TABLE "public"."service_tickets" ADD CONSTRAINT "service_tickets_request_type_length" CHECK (length(TRIM(BOTH FROM request_type)) >= 1 AND length(TRIM(BOTH FROM request_type)) <= 500);

ALTER TABLE "public"."service_tickets" ADD CONSTRAINT "service_tickets_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'resolved'::text]));

ALTER TABLE "public"."service_tickets" ADD CONSTRAINT "service_tickets_table_number_clean" CHECK (table_number ~ '^[A-Za-z0-9 _-]{1,20}$'::text);

ALTER TABLE "public"."table_configurations" ADD CONSTRAINT "table_configurations_no_self_merge" CHECK (source_table <> target_table);

ALTER TABLE "public"."table_configurations" ADD CONSTRAINT "table_configurations_source_clean" CHECK (source_table ~ '^[A-Za-z0-9 _-]{1,20}$'::text);

ALTER TABLE "public"."table_configurations" ADD CONSTRAINT "table_configurations_target_clean" CHECK (target_table ~ '^[A-Za-z0-9 _-]{1,20}$'::text);

ALTER TABLE "public"."admin_users" ADD CONSTRAINT "admin_users_pkey" PRIMARY KEY (user_id);

ALTER TABLE "public"."menu_events" ADD CONSTRAINT "menu_events_pkey" PRIMARY KEY (id);

ALTER TABLE "public"."menu_items" ADD CONSTRAINT "menu_items_pkey" PRIMARY KEY (id);

ALTER TABLE "public"."restaurant_clients" ADD CONSTRAINT "restaurant_clients_pkey" PRIMARY KEY (id);

ALTER TABLE "public"."restaurant_settings" ADD CONSTRAINT "restaurant_settings_pkey" PRIMARY KEY (id);

ALTER TABLE "public"."service_tickets" ADD CONSTRAINT "service_tickets_pkey" PRIMARY KEY (id);

ALTER TABLE "public"."table_configurations" ADD CONSTRAINT "table_configurations_pkey" PRIMARY KEY (source_table, target_table);

ALTER TABLE "public"."tenant_memberships" ADD CONSTRAINT "tenant_memberships_pkey" PRIMARY KEY (id);

ALTER TABLE "public"."tenants" ADD CONSTRAINT "tenants_pkey" PRIMARY KEY (id);

ALTER TABLE "public"."restaurant_clients" ADD CONSTRAINT "restaurant_clients_client_slug_key" UNIQUE (client_slug);

ALTER TABLE "public"."tenant_memberships" ADD CONSTRAINT "tenant_memberships_tenant_user_key" UNIQUE (tenant_id, user_id);

ALTER TABLE "public"."tenants" ADD CONSTRAINT "tenants_client_slug_key" UNIQUE (client_slug);

ALTER TABLE "public"."admin_users" ADD CONSTRAINT "admin_users_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."menu_events" ADD CONSTRAINT "menu_events_item_id_fkey" FOREIGN KEY (item_id) REFERENCES menu_items(id) ON DELETE SET NULL;

ALTER TABLE "public"."menu_events" ADD CONSTRAINT "menu_events_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id);

ALTER TABLE "public"."menu_items" ADD CONSTRAINT "menu_items_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id);

ALTER TABLE "public"."restaurant_settings" ADD CONSTRAINT "restaurant_settings_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id);

ALTER TABLE "public"."service_tickets" ADD CONSTRAINT "service_tickets_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id);

ALTER TABLE "public"."table_configurations" ADD CONSTRAINT "table_configurations_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id);

ALTER TABLE "public"."tenant_memberships" ADD CONSTRAINT "tenant_memberships_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."tenant_memberships" ADD CONSTRAINT "tenant_memberships_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX idx_master_clients_slug ON public.restaurant_clients USING btree (client_slug);

CREATE INDEX idx_menu_events_metrics ON public.menu_events USING btree (client_slug, event_type);

CREATE INDEX idx_menu_sort ON public.menu_items USING btree (sort_order);

CREATE INDEX idx_tickets_pending ON public.service_tickets USING btree (status) WHERE (status = 'pending'::text);

CREATE INDEX menu_events_tenant_id_idx ON public.menu_events USING btree (tenant_id);

CREATE INDEX menu_items_tenant_id_idx ON public.menu_items USING btree (tenant_id);

CREATE INDEX restaurant_settings_tenant_id_idx ON public.restaurant_settings USING btree (tenant_id);

CREATE INDEX service_tickets_tenant_id_idx ON public.service_tickets USING btree (tenant_id);

CREATE INDEX table_configurations_tenant_id_idx ON public.table_configurations USING btree (tenant_id);

CREATE INDEX tenant_memberships_tenant_id_idx ON public.tenant_memberships USING btree (tenant_id);

CREATE INDEX tenant_memberships_user_id_idx ON public.tenant_memberships USING btree (user_id);

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
BEGIN
  IF auth.uid() IS NULL THEN RETURN false; END IF;
  RETURN EXISTS (SELECT 1 FROM public.admin_users WHERE public.admin_users.user_id=auth.uid());
END
$function$;

ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION public.sanitize_text()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_TABLE_NAME = 'menu_items' THEN
        IF NEW.name IS NOT NULL THEN
            NEW.name := regexp_replace(NEW.name, '<[^>]*>', '', 'g');
        END IF;

        IF NEW.description IS NOT NULL THEN
            NEW.description := regexp_replace(NEW.description, '<[^>]*>', '', 'g');
        END IF;

        IF NEW.image_url IS NOT NULL AND NEW.image_url !~* '^https?://' THEN
            NEW.image_url := NULL;
        END IF;
    END IF;

    IF TG_TABLE_NAME = 'restaurant_settings' THEN
        IF NEW.restaurant_name IS NOT NULL THEN
            NEW.restaurant_name := regexp_replace(NEW.restaurant_name, '<[^>]*>', '', 'g');
        END IF;

        IF NEW.logo_url IS NOT NULL AND NEW.logo_url !~* '^https?://' THEN
            NEW.logo_url := NULL;
        END IF;
    END IF;

    IF TG_TABLE_NAME = 'service_tickets' THEN
        IF NEW.request_type IS NOT NULL THEN
            NEW.request_type := regexp_replace(NEW.request_type, '<[^>]*>', '', 'g');
        END IF;
    END IF;

    RETURN NEW;
END;
$function$;

ALTER FUNCTION "public"."sanitize_text"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION ting_private.assign_service_ticket_tenant()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  resolved_tenant_id uuid;
begin
  if tg_table_schema <> 'public'
     or tg_table_name <> 'service_tickets'
     or tg_when <> 'BEFORE'
     or tg_level <> 'ROW'
     or tg_op not in ('INSERT', 'UPDATE') then
    raise exception 'assign_service_ticket_tenant may only run as the approved public.service_tickets row trigger'
      using errcode = '42501';
  end if;

  if tg_op = 'UPDATE' then
    if new.client_slug is distinct from old.client_slug
       or new.tenant_id is distinct from old.tenant_id then
      raise exception 'service ticket ownership cannot be changed after creation'
        using errcode = '23514';
    end if;
    return new;
  end if;

  -- Compatibility window: the deployed legacy customer page sends neither field.
  if new.client_slug is null then
    if new.tenant_id is not null then
      raise exception 'tenant_id requires client_slug for canonical verification'
        using errcode = '23514';
    end if;
    return new;
  end if;

  select tenant.id
    into resolved_tenant_id
    from public.tenants as tenant
   where tenant.client_slug = new.client_slug;

  if resolved_tenant_id is null then
    raise exception 'unknown client_slug'
      using errcode = '23514';
  end if;

  if new.tenant_id is not null and new.tenant_id <> resolved_tenant_id then
    raise exception 'tenant_id does not match client_slug'
      using errcode = '23514';
  end if;

  new.tenant_id := resolved_tenant_id;
  return new;
end;
$function$;

ALTER FUNCTION "ting_private"."assign_service_ticket_tenant"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION ting_private.assign_tenant_id_from_client_slug()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
    resolved_tenant_id UUID;
BEGIN
    IF TG_OP <> 'INSERT'
       OR TG_TABLE_SCHEMA <> 'public'
       OR TG_TABLE_NAME NOT IN ('menu_items', 'menu_events') THEN
        RAISE EXCEPTION
            'assign_tenant_id_from_client_slug may only run for approved INSERT triggers';
    END IF;

    IF NEW.client_slug IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT tenant.id
    INTO resolved_tenant_id
    FROM public.tenants AS tenant
    WHERE tenant.client_slug = NEW.client_slug;

    IF NEW.tenant_id IS NULL THEN
        NEW.tenant_id := resolved_tenant_id;

    ELSIF resolved_tenant_id IS NULL
          OR NEW.tenant_id <> resolved_tenant_id THEN
        RAISE EXCEPTION
            'tenant_id does not match client_slug'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$function$;

ALTER FUNCTION "ting_private"."assign_tenant_id_from_client_slug"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION ting_private.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE cmd record;
BEGIN
  FOR cmd IN SELECT * FROM pg_event_trigger_ddl_commands() WHERE command_tag IN ('CREATE TABLE','CREATE TABLE AS','SELECT INTO') AND object_type IN ('table','partitioned table')
  LOOP
    IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security',cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %',cmd.object_identity;
      EXCEPTION WHEN OTHERS THEN
        RAISE LOG 'rls_auto_enable: failed to enable RLS on %',cmd.object_identity;
      END;
    ELSE
      RAISE LOG 'rls_auto_enable: skip % (schema: %)',cmd.object_identity,cmd.schema_name;
    END IF;
  END LOOP;
END
$function$;

ALTER FUNCTION "ting_private"."rls_auto_enable"() OWNER TO "postgres";

CREATE TRIGGER menu_events_assign_tenant_id BEFORE INSERT ON menu_events FOR EACH ROW EXECUTE FUNCTION ting_private.assign_tenant_id_from_client_slug();

ALTER TABLE "public"."menu_events" ENABLE TRIGGER "menu_events_assign_tenant_id";

CREATE TRIGGER clean_menu_items_trigger BEFORE INSERT OR UPDATE ON menu_items FOR EACH ROW EXECUTE FUNCTION sanitize_text();

ALTER TABLE "public"."menu_items" ENABLE TRIGGER "clean_menu_items_trigger";

CREATE TRIGGER menu_items_assign_tenant_id BEFORE INSERT ON menu_items FOR EACH ROW EXECUTE FUNCTION ting_private.assign_tenant_id_from_client_slug();

ALTER TABLE "public"."menu_items" ENABLE TRIGGER "menu_items_assign_tenant_id";

CREATE TRIGGER clean_restaurant_settings_trigger BEFORE INSERT OR UPDATE ON restaurant_settings FOR EACH ROW EXECUTE FUNCTION sanitize_text();

ALTER TABLE "public"."restaurant_settings" ENABLE TRIGGER "clean_restaurant_settings_trigger";

CREATE TRIGGER a_assign_service_ticket_tenant BEFORE INSERT OR UPDATE ON service_tickets FOR EACH ROW EXECUTE FUNCTION ting_private.assign_service_ticket_tenant();

ALTER TABLE "public"."service_tickets" ENABLE TRIGGER "a_assign_service_ticket_tenant";

CREATE TRIGGER clean_service_tickets_trigger BEFORE INSERT OR UPDATE ON service_tickets FOR EACH ROW EXECUTE FUNCTION sanitize_text();

ALTER TABLE "public"."service_tickets" ENABLE TRIGGER "clean_service_tickets_trigger";

CREATE POLICY "Admins can read own admin allowlist row" ON "public"."admin_users" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));

CREATE POLICY "Admins can delete menu analytics" ON "public"."menu_events" AS PERMISSIVE FOR DELETE TO "authenticated" USING (is_admin());

CREATE POLICY "Admins can read menu analytics" ON "public"."menu_events" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_admin());

CREATE POLICY "Public can insert menu analytics" ON "public"."menu_events" AS PERMISSIVE FOR INSERT TO "anon", "authenticated" WITH CHECK (((event_type = ANY (ARRAY['menu_view'::text, 'item_viewed'::text, 'filter_used'::text, 'assistance_requested'::text])) AND (client_slug ~ '^[A-Za-z0-9_-]{1,80}$'::text) AND ((metadata IS NULL) OR (jsonb_typeof(metadata) = 'object'::text))));

CREATE POLICY "Admins can delete menu items" ON "public"."menu_items" AS PERMISSIVE FOR DELETE TO "authenticated" USING (is_admin());

CREATE POLICY "Admins can insert menu items" ON "public"."menu_items" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((is_admin() AND (price >= (0)::numeric) AND ((promo_price IS NULL) OR (promo_price >= (0)::numeric))));

CREATE POLICY "Admins can update menu items" ON "public"."menu_items" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (is_admin()) WITH CHECK ((is_admin() AND (price >= (0)::numeric) AND ((promo_price IS NULL) OR (promo_price >= (0)::numeric))));

CREATE POLICY "Public can read menu items" ON "public"."menu_items" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);

CREATE POLICY "Admins can delete client routing config" ON "public"."restaurant_clients" AS PERMISSIVE FOR DELETE TO "authenticated" USING (is_admin());

CREATE POLICY "Admins can insert client routing config" ON "public"."restaurant_clients" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (is_admin());

CREATE POLICY "Admins can update client routing config" ON "public"."restaurant_clients" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "Public can read client routing config" ON "public"."restaurant_clients" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);

CREATE POLICY "Admins can delete restaurant settings" ON "public"."restaurant_settings" AS PERMISSIVE FOR DELETE TO "authenticated" USING (is_admin());

CREATE POLICY "Admins can insert restaurant settings" ON "public"."restaurant_settings" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (is_admin());

CREATE POLICY "Admins can update restaurant settings" ON "public"."restaurant_settings" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "Public can read restaurant settings" ON "public"."restaurant_settings" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);

CREATE POLICY "Admins can delete service tickets" ON "public"."service_tickets" AS PERMISSIVE FOR DELETE TO "authenticated" USING (is_admin());

CREATE POLICY "Admins can read service tickets" ON "public"."service_tickets" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_admin());

CREATE POLICY "Admins can update service tickets" ON "public"."service_tickets" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (is_admin()) WITH CHECK ((is_admin() AND (status = ANY (ARRAY['pending'::text, 'resolved'::text]))));

CREATE POLICY "Public can create pending service tickets" ON "public"."service_tickets" AS PERMISSIVE FOR INSERT TO "anon", "authenticated" WITH CHECK (((status = 'pending'::text) AND (table_number ~ '^[A-Za-z0-9 _-]{1,20}$'::text) AND (request_type IS NOT NULL) AND ((length(TRIM(BOTH FROM request_type)) >= 1) AND (length(TRIM(BOTH FROM request_type)) <= 500)) AND (client_slug IS NOT NULL) AND (tenant_id IS NOT NULL)));

CREATE POLICY "Admins can delete table configurations" ON "public"."table_configurations" AS PERMISSIVE FOR DELETE TO "authenticated" USING (is_admin());

CREATE POLICY "Admins can insert table configurations" ON "public"."table_configurations" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((is_admin() AND (source_table ~ '^[A-Za-z0-9 _-]{1,20}$'::text) AND (target_table ~ '^[A-Za-z0-9 _-]{1,20}$'::text) AND (source_table <> target_table)));

CREATE POLICY "Admins can update table configurations" ON "public"."table_configurations" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (is_admin()) WITH CHECK ((is_admin() AND (source_table ~ '^[A-Za-z0-9 _-]{1,20}$'::text) AND (target_table ~ '^[A-Za-z0-9 _-]{1,20}$'::text) AND (source_table <> target_table)));

CREATE POLICY "Public can read table configurations" ON "public"."table_configurations" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);

CREATE POLICY "Admins can delete menu pictures" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO "authenticated" USING (((bucket_id = 'menu-pictures'::text) AND is_admin()));

CREATE POLICY "Admins can update menu pictures" ON "storage"."objects" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (((bucket_id = 'menu-pictures'::text) AND is_admin())) WITH CHECK (((bucket_id = 'menu-pictures'::text) AND is_admin()));

CREATE POLICY "Admins can upload menu pictures" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (((bucket_id = 'menu-pictures'::text) AND is_admin()));

CREATE POLICY "Public can view menu pictures" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING ((bucket_id = 'menu-pictures'::text));

ALTER TABLE "public"."admin_users" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."admin_users" NO FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."admin_users" REPLICA IDENTITY DEFAULT;

ALTER TABLE "public"."menu_events" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."menu_events" NO FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."menu_events" REPLICA IDENTITY DEFAULT;

ALTER TABLE "public"."menu_items" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."menu_items" NO FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."menu_items" REPLICA IDENTITY DEFAULT;

ALTER TABLE "public"."restaurant_clients" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."restaurant_clients" NO FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."restaurant_clients" REPLICA IDENTITY DEFAULT;

ALTER TABLE "public"."restaurant_settings" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."restaurant_settings" NO FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."restaurant_settings" REPLICA IDENTITY DEFAULT;

ALTER TABLE "public"."service_tickets" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."service_tickets" NO FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."service_tickets" REPLICA IDENTITY DEFAULT;

ALTER TABLE "public"."table_configurations" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."table_configurations" NO FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."table_configurations" REPLICA IDENTITY DEFAULT;

ALTER TABLE "public"."tenant_memberships" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tenant_memberships" NO FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."tenant_memberships" REPLICA IDENTITY DEFAULT;

ALTER TABLE "public"."tenants" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tenants" NO FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."tenants" REPLICA IDENTITY DEFAULT;

ALTER SCHEMA "ting_private" OWNER TO "postgres";

REVOKE ALL ON SCHEMA "ting_private" FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT USAGE, CREATE ON SCHEMA "ting_private" TO "postgres";

ALTER SCHEMA "public" OWNER TO "pg_database_owner";

REVOKE ALL ON SCHEMA "public" FROM PUBLIC, "anon", "authenticated", "pg_database_owner", "postgres", "service_role";

GRANT USAGE, CREATE ON SCHEMA "public" TO "pg_database_owner";

GRANT USAGE ON SCHEMA "public" TO PUBLIC;

GRANT USAGE ON SCHEMA "public" TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "anon";

GRANT USAGE ON SCHEMA "public" TO "authenticated";

GRANT USAGE ON SCHEMA "public" TO "service_role";

REVOKE ALL ON TABLE "public"."admin_users" FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."admin_users" TO "postgres";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."admin_users" TO "anon";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."admin_users" TO "authenticated";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."admin_users" TO "service_role";

REVOKE ALL ON TABLE "public"."menu_events" FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."menu_events" TO "postgres";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."menu_events" TO "anon";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."menu_events" TO "authenticated";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."menu_events" TO "service_role";

REVOKE ALL ON TABLE "public"."menu_items" FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."menu_items" TO "postgres";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."menu_items" TO "anon";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."menu_items" TO "authenticated";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."menu_items" TO "service_role";

REVOKE ALL ON TABLE "public"."restaurant_clients" FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."restaurant_clients" TO "postgres";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."restaurant_clients" TO "anon";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."restaurant_clients" TO "authenticated";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."restaurant_clients" TO "service_role";

REVOKE ALL ON TABLE "public"."restaurant_settings" FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."restaurant_settings" TO "postgres";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."restaurant_settings" TO "anon";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."restaurant_settings" TO "authenticated";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."restaurant_settings" TO "service_role";

REVOKE ALL ON TABLE "public"."service_tickets" FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."service_tickets" TO "postgres";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."service_tickets" TO "anon";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."service_tickets" TO "authenticated";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."service_tickets" TO "service_role";

REVOKE ALL ON TABLE "public"."table_configurations" FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."table_configurations" TO "postgres";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."table_configurations" TO "anon";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."table_configurations" TO "authenticated";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."table_configurations" TO "service_role";

REVOKE ALL ON TABLE "public"."tenant_memberships" FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."tenant_memberships" TO "postgres";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."tenant_memberships" TO "service_role";

REVOKE ALL ON TABLE "public"."tenants" FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."tenants" TO "postgres";

GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE "public"."tenants" TO "service_role";

REVOKE ALL ON FUNCTION "public"."is_admin"() FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO "anon";

GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO "authenticated";

GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO "service_role";

REVOKE ALL ON FUNCTION "public"."sanitize_text"() FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."sanitize_text"() TO PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."sanitize_text"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."sanitize_text"() TO "anon";

GRANT EXECUTE ON FUNCTION "public"."sanitize_text"() TO "authenticated";

GRANT EXECUTE ON FUNCTION "public"."sanitize_text"() TO "service_role";

REVOKE ALL ON FUNCTION "ting_private"."assign_service_ticket_tenant"() FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "ting_private"."assign_service_ticket_tenant"() TO "postgres";

REVOKE ALL ON FUNCTION "ting_private"."assign_tenant_id_from_client_slug"() FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "ting_private"."assign_tenant_id_from_client_slug"() TO "postgres";

REVOKE ALL ON FUNCTION "ting_private"."rls_auto_enable"() FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "ting_private"."rls_auto_enable"() TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES  FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLES  TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLES  TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLES  TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS  FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT EXECUTE ON FUNCTIONS  TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT EXECUTE ON FUNCTIONS  TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT EXECUTE ON FUNCTIONS  TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT EXECUTE ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES  FROM PUBLIC, "anon", "authenticated", "postgres", "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT, UPDATE, USAGE ON SEQUENCES  TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT, UPDATE, USAGE ON SEQUENCES  TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT, UPDATE, USAGE ON SEQUENCES  TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT, UPDATE, USAGE ON SEQUENCES  TO "service_role";

DO $pub$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN EXECUTE 'CREATE PUBLICATION "supabase_realtime"'; END IF; END $pub$;

ALTER PUBLICATION "supabase_realtime" SET (publish = 'insert, update, delete, truncate', publish_via_partition_root = false);

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."restaurant_settings";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."menu_items";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."service_tickets";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."table_configurations";

INSERT INTO storage.buckets (id,name,public,file_size_limit,allowed_mime_types) VALUES ('menu-pictures','menu-pictures',true,1048576,ARRAY['image/jpeg', 'image/png', 'image/webp']::text[]);

CREATE EVENT TRIGGER "ensure_rls" ON ddl_command_end WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO') EXECUTE FUNCTION ting_private.rls_auto_enable();

ALTER EVENT TRIGGER "ensure_rls" OWNER TO "postgres";

ALTER EVENT TRIGGER "ensure_rls" ENABLE;

COMMIT;
