import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createClient} from '@supabase/supabase-js';
import {historicalFiles} from './history.mjs';
import {verifyIsolation,migration,migrationName,A,B} from '../../tests/ting2/verify.mjs';
import {verifyMenuItems,menuMigration,menuMigrationName} from '../../tests/ting2/menu-items.mjs';
import {verifyMenuEvents,eventMigration,eventMigrationName} from '../../tests/ting2/menu-events.mjs';
import {verifyServiceTickets,ticketMigration,ticketMigrationName} from '../../tests/ting2/service-tickets.mjs';
import {verifyRoutingPreparation,routingMigration,routingMigrationName} from '../../tests/ting2/routing-prepare.mjs';
import {verifyRoutingScope,routeScopeMigration,routeScopeMigrationName} from '../../tests/ting2/routing-scope.mjs';
export async function rehearseTing2(db,status,report,command,workdir) {
 const pass=label=>{report.checks.push(label);console.log('PASS: '+label);};
 const directory=join(workdir,'supabase/migrations');mkdirSync(directory,{recursive:true});
 const history=historicalFiles();
 for(const f of history)writeFileSync(join(directory,f.filename),f.sql);
 command(['migration','repair',...history.map(r=>r.version),'--local','--status','applied']);
 for(const f of history)await db.query('UPDATE supabase_migrations.schema_migrations SET name=$2,statements=$3 WHERE version=$1',[f.version,f.name,[f.sql]]);
 const ledger=async()=>(await db.query('SELECT version,name,md5(array_to_string(statements,chr(10))) AS statements_md5 FROM supabase_migrations.schema_migrations ORDER BY version')).rows;
 const before=await ledger();
 await verifyIsolation(db,pass,async()=>{
  writeFileSync(join(directory,migrationName),migration);
  command(['db','push','--local','--dry-run','--skip-vault','--yes']);
  assert.deepEqual(await ledger(),before);
  assert.equal((await db.query("SELECT to_regprocedure('public.request_tenant_id()') AS f")).rows[0].f,null);
  command(['db','push','--local','--skip-vault','--yes']);
  const applied=await ledger();assert.equal(applied.length,before.length+1);assert.deepEqual(applied.slice(0,-1),before);
  assert.equal(applied.at(-1).version,migrationName.split('_')[0]);
  command(['db','push','--local','--skip-vault','--yes']);assert.deepEqual(await ledger(),applied);
  pass('Actual TING-2 migration: native CLI dry-run, apply once and repeated no-op; original history unchanged');
 });
 await verifyMenuItems(db,pass,async()=>{
  const beforeMenu=await ledger();
  writeFileSync(join(directory,menuMigrationName),menuMigration);
  command(['db','push','--local','--dry-run','--skip-vault','--yes']);
  assert.deepEqual(await ledger(),beforeMenu);
  assert.equal((await db.query("SELECT to_regprocedure('ting_private.prevent_menu_item_reassignment()') AS f")).rows[0].f,null);
  command(['db','push','--local','--skip-vault','--yes']);
  const applied=await ledger();assert.equal(applied.length,beforeMenu.length+1);assert.deepEqual(applied.slice(0,-1),beforeMenu);
  assert.equal(applied.at(-1).version,menuMigrationName.split('_')[0]);
  command(['db','push','--local','--skip-vault','--yes']);assert.deepEqual(await ledger(),applied);
  pass('Actual menu-item migration: native CLI dry-run, apply once and repeated no-op; prior ledger unchanged');
 });
 await verifyMenuEvents(db,pass,async()=>{
  const beforeEvents=await ledger();
  writeFileSync(join(directory,eventMigrationName),eventMigration);
  command(['db','push','--local','--dry-run','--skip-vault','--yes']);
  assert.deepEqual(await ledger(),beforeEvents);
  assert.equal((await db.query("SELECT is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='menu_events' AND column_name='tenant_id'")).rows[0].is_nullable,'YES');
  command(['db','push','--local','--skip-vault','--yes']);
  const applied=await ledger();assert.equal(applied.length,beforeEvents.length+1);assert.deepEqual(applied.slice(0,-1),beforeEvents);
  assert.equal(applied.at(-1).version,eventMigrationName.split('_')[0]);
  command(['db','push','--local','--skip-vault','--yes']);assert.deepEqual(await ledger(),applied);
  pass('Actual menu-event migration: native CLI dry-run, apply once and repeated no-op; prior ledger unchanged');
 });
 await verifyServiceTickets(db,pass,async()=>{
  const beforeTickets=await ledger();
  writeFileSync(join(directory,ticketMigrationName),ticketMigration);
  command(['db','push','--local','--dry-run','--skip-vault','--yes']);
  assert.deepEqual(await ledger(),beforeTickets);
  assert.equal((await db.query("SELECT is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='service_tickets' AND column_name='client_slug'")).rows[0].is_nullable,'YES');
  command(['db','push','--local','--skip-vault','--yes']);
  const applied=await ledger();assert.equal(applied.length,beforeTickets.length+1);assert.deepEqual(applied.slice(0,-1),beforeTickets);
  assert.equal(applied.at(-1).version,ticketMigrationName.split('_')[0]);
  command(['db','push','--local','--skip-vault','--yes']);assert.deepEqual(await ledger(),applied);
  pass('Actual service-ticket migration: native CLI dry-run, apply once and repeated no-op; prior ledger unchanged');
 });
 await verifyRoutingPreparation(db,pass,async()=>{
  const beforeRouting=await ledger();
  writeFileSync(join(directory,routingMigrationName),routingMigration);
  command(['db','push','--local','--dry-run','--skip-vault','--yes']);
  assert.deepEqual(await ledger(),beforeRouting);
  command(['db','push','--local','--skip-vault','--yes']);
  const applied=await ledger();assert.equal(applied.length,beforeRouting.length+1);assert.deepEqual(applied.slice(0,-1),beforeRouting);
  assert.equal(applied.at(-1).version,routingMigrationName.split('_')[0]);
  command(['db','push','--local','--skip-vault','--yes']);assert.deepEqual(await ledger(),applied);
  pass('Actual routing migration: native CLI dry-run, apply once and repeated no-op; prior ledger unchanged');
 });
 await verifyRoutingScope(db,pass,async()=>{
  const beforeScope=await ledger();
  writeFileSync(join(directory,routeScopeMigrationName),routeScopeMigration);
  command(['db','push','--local','--dry-run','--skip-vault','--yes']);
  assert.deepEqual(await ledger(),beforeScope);
  command(['db','push','--local','--skip-vault','--yes']);
  const applied=await ledger();assert.equal(applied.length,beforeScope.length+1);assert.deepEqual(applied.slice(0,-1),beforeScope);
  assert.equal(applied.at(-1).version,routeScopeMigrationName.split('_')[0]);
  command(['db','push','--local','--skip-vault','--yes']);assert.deepEqual(await ledger(),applied);
  pass('Routing scope migration: native CLI dry-run, apply once, repeated no-op and prior ledger preserved');
 });
 const options={auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}};
 const service=createClient(status.API_URL,status.SERVICE_ROLE_KEY,options);
 const visitor=createClient(status.API_URL,status.ANON_KEY,{...options,global:{headers:{'x-client-slug':'test-a'}}});
 const missing=createClient(status.API_URL,status.ANON_KEY,options);
 const admin=createClient(status.API_URL,status.ANON_KEY,{...options,global:{headers:{'x-client-slug':'test-b'}}});
 const ok=(r,label)=>{assert(!r.error,label);return r.data;};
 try {
  let ready=false;
  for(let i=0;i<30;i++) {const r=await visitor.rpc('request_tenant_id');if(!r.error&&r.data===A){ready=true;break;}await new Promise(r=>setTimeout(r,500));}
  assert(ready,'PostgREST release schema cache ready');
  assert.equal(ok(await missing.rpc('request_tenant_id'),'Missing route RPC'),null);
  assert.deepEqual(ok(await missing.from('restaurant_clients').select('client_slug'),'Old bootstrap compatibility'),[{client_slug:'the-bistro'}]);
  assert.equal(ok(await visitor.from('restaurant_clients').select('client_slug').eq('client_slug','test-a'),'Routed master bootstrap').length,1);
  const routeB=createClient(status.API_URL,status.ANON_KEY,{...options,global:{headers:{'x-client-slug':'test-b'}}});
  const unknownRoute=createClient(status.API_URL,status.ANON_KEY,{...options,global:{headers:{'x-client-slug':'unknown'}}});
  assert.deepEqual(ok(await routeB.from('restaurant_clients').select('client_slug'),'Forged known public route'),[{client_slug:'test-b'}]);
  assert.equal(ok(await routeB.from('restaurant_clients').select('client_slug').eq('client_slug','the-bistro'),'Wrong header plus filter').length,0);
  assert.equal(ok(await unknownRoute.from('restaurant_clients').select('client_slug'),'Unknown header').length,0);
  assert((await visitor.from('restaurant_clients').update({restaurant_name:'blocked'}).eq('client_slug','test-a')).error,'Public registry write denied');
  assert((await visitor.from('admin_users').select('user_id')).error,'Public legacy allowlist denied');
  assert.deepEqual(ok(await visitor.from('restaurant_settings').select('tenant_id'),'Public settings'),[{tenant_id:A}]);
  assert.equal(ok(await missing.from('restaurant_settings').select('*'),'Missing context settings').length,0);
  const routedMenu=ok(await visitor.from('menu_items').select('tenant_id'),'Routed public menu');
  assert(routedMenu.length>0 && routedMenu.every(row=>row.tenant_id===A));
  assert.equal(ok(await missing.from('menu_items').select('*'),'Missing context menu').length,0);
  assert((await visitor.from('table_configurations').select('*')).error,'Anonymous table links blocked');
  const email='ting2-'+randomUUID()+'@example.com',password=randomUUID()+'Aa1!';
  const user=ok(await service.auth.admin.createUser({email,password,email_confirm:true}),'Create tenant admin').user;
  await db.query('INSERT INTO public.tenant_memberships(tenant_id,user_id,role) VALUES ($1,$2,$3)',[A,user.id,'owner']);
  ok(await admin.auth.signInWithPassword({email,password}),'Real tenant admin login');
  assert.deepEqual(ok(await admin.from('restaurant_clients').select('client_slug'),'Authenticated public route'),[{client_slug:'test-b'}]);
  // Header deliberately points to B: authorization still derives from membership A.
  assert.deepEqual(ok(await admin.from('table_configurations').select('tenant_id'),'Member links'),[{tenant_id:A}]);
  for(let i=0;i<2;i++)ok(await admin.from('table_configurations').upsert({tenant_id:A,source_table:'10',target_table:'11'},{onConflict:'tenant_id,source_table,target_table'}),'Repeated REST upsert');
  assert((await admin.from('table_configurations').insert({tenant_id:B,source_table:'10',target_table:'11'})).error,'Foreign REST insert blocked');
  assert.equal(ok(await admin.from('table_configurations').update({target_table:'19'}).eq('tenant_id',B).select(),'Foreign update').length,0);
  assert.equal(ok(await admin.from('table_configurations').delete().eq('tenant_id',B).select(),'Foreign delete').length,0);
  ok(await admin.from('table_configurations').delete().eq('tenant_id',A).eq('source_table','10'),'Own delete');
  const ownMenu=ok(await admin.from('menu_items').insert({tenant_id:A,client_slug:'test-a',name:'REST own',price:3}).select('id').single(),'Own menu insert');
  assert((await admin.from('menu_items').insert({tenant_id:B,client_slug:'test-b',name:'REST foreign',price:3})).error,'Foreign menu insert blocked');
  assert.equal(ok(await admin.from('menu_items').update({name:'foreign'}).eq('tenant_id',B).select(),'Foreign menu update').length,0);
  ok(await admin.from('menu_items').delete().eq('id',ownMenu.id).eq('tenant_id',A),'Own menu delete');
  const ownEventId=randomUUID();
  ok(await visitor.from('menu_events').insert({id:ownEventId,tenant_id:A,client_slug:'test-a',event_type:'menu_view'}),'Routed event insert');
  assert((await visitor.from('menu_events').select('id')).error,'Anonymous event read blocked');
  assert((await visitor.from('menu_events').insert({tenant_id:B,client_slug:'test-b',event_type:'menu_view'})).error,'Foreign-route event insert blocked');
  assert.equal(ok(await admin.from('menu_events').select('tenant_id'),'Member analytics').every(row=>row.tenant_id===A),true);
  assert.equal(ok(await admin.from('menu_events').delete().eq('tenant_id',B).select(),'Foreign event delete').length,0);
  ok(await admin.from('menu_events').delete().eq('id',ownEventId).eq('tenant_id',A),'Own event delete');
  const ownTicketId=randomUUID();
  ok(await visitor.from('service_tickets').insert({id:ownTicketId,table_number:'7',request_type:'REST assistance'}),'Routed ticket insert');
  const ownTicket=(await db.query('SELECT tenant_id,client_slug FROM public.service_tickets WHERE id=$1',[ownTicketId])).rows[0];
  assert.equal(ownTicket.tenant_id,A);assert.equal(ownTicket.client_slug,'test-a');
  assert((await visitor.from('service_tickets').select('id')).error,'Anonymous ticket read blocked');
  assert.equal(ok(await admin.from('service_tickets').select('tenant_id'),'Member tickets').every(row=>row.tenant_id===A),true);
  ok(await admin.from('service_tickets').update({status:'resolved'}).eq('id',ownTicketId).eq('tenant_id',A),'Own ticket resolve');
  assert.equal(ok(await admin.from('service_tickets').update({status:'resolved'}).eq('tenant_id',B).select(),'Foreign ticket update').length,0);
  assert((await admin.from('service_tickets').delete().eq('id',ownTicketId)).error,'Client ticket delete blocked');
  await db.query('DELETE FROM public.tenant_memberships WHERE user_id=$1',[user.id]);
  assert.equal(ok(await admin.from('table_configurations').select('*'),'Revoked membership').length,0);
  assert.equal(ok(await admin.from('menu_items').update({name:'revoked'}).eq('tenant_id',A).select(),'Revoked menu write').length,0);
  assert.equal(ok(await admin.from('menu_events').select('id'),'Revoked analytics read').length,0);
  assert.equal(ok(await admin.from('service_tickets').select('id'),'Revoked ticket read').length,0);
  pass('Real Auth/REST: routed settings, menu, analytics and tickets; tenant operations, forged-route denial and immediate revocation');
 } finally {await Promise.allSettled([service.removeAllChannels(),visitor.removeAllChannels(),missing.removeAllChannels(),admin.removeAllChannels()]);}
}
