import assert from 'node:assert/strict';
import {readFileSync,readdirSync,mkdirSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {historicalFiles} from './history.mjs';

const migrations = fileURLToPath(new URL('../../migrations/',import.meta.url));
const target = '20260923194905_ting4_restrict_menu_picture_listing.sql';
export async function rehearseTing4(db,{admin,ordinary,visitor},report,command,workdir,status) {
  const pass = label => { report.checks.push(label);console.log('PASS: '+label); };
  const ok = (r,label) => { assert(!r.error,`${label} failed`);return r.data; };
  const files = readdirSync(migrations).filter(name=>/^\d+_.*\.sql$/.test(name) && name!==target).sort();
  historicalFiles();
  assert.equal(files.length,15,'Unexpected source migration count');
  const directory = join(workdir,'supabase/migrations');mkdirSync(directory,{recursive:true});
  for (const file of files) writeFileSync(join(directory,file),readFileSync(join(migrations,file)));
  command(['migration','repair',...files.map(file=>file.split('_')[0]),'--local','--status','applied']);
  const ledger = async()=>(await db.query('SELECT version FROM supabase_migrations.schema_migrations ORDER BY version')).rows.map(r=>r.version);
  const oldLedger=await ledger();
  assert.deepEqual(oldLedger,files.map(file=>file.split('_')[0]));
  const before=(await db.query("SELECT policyname,cmd,roles,qual,with_check FROM pg_policies WHERE schemaname='storage' AND tablename='objects' ORDER BY policyname")).rows;
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
  const name='ting4-list-check.png';
  ok(await admin.storage.from('menu-pictures').upload(name,png,{contentType:'image/png',upsert:false}),'Initial admin upload');
  assert(ok(await visitor.storage.from('menu-pictures').list(),'Initial anon list').some(r=>r.name===name));
  assert(ok(await ordinary.storage.from('menu-pictures').list(),'Initial ordinary list').some(r=>r.name===name));
  pass('Storage API reproduces anonymous and ordinary enumeration');
  const publicUrl=admin.storage.from('menu-pictures').getPublicUrl(name).data.publicUrl;
  assert.equal(new URL(publicUrl).origin,new URL(status.API_URL).origin);
  const original=await fetch(publicUrl,{signal:AbortSignal.timeout(10000)});
  assert(original.ok);
  assert.deepEqual(Buffer.from(await original.arrayBuffer()),png);
  writeFileSync(join(directory,target),readFileSync(join(migrations,target)));
  command(['db','push','--local','--dry-run','--skip-vault','--yes']);
  assert.deepEqual(await ledger(),oldLedger);
  assert(ok(await visitor.storage.from('menu-pictures').list(),'Dry-run list').some(r=>r.name===name));
  command(['db','push','--local','--skip-vault','--yes']);
  assert.deepEqual(await ledger(),[...oldLedger,target.split('_')[0]]);
  command(['db','push','--local','--skip-vault','--yes']);
  assert.deepEqual(await ledger(),[...oldLedger,target.split('_')[0]]);
  pass('CLI dry-run, apply once and repeated no-op preserve fifteen prior versions');
  assert.deepEqual(ok(await visitor.storage.from('menu-pictures').list(),'Anon list after change'),[]);
  assert.deepEqual(ok(await ordinary.storage.from('menu-pictures').list(),'Ordinary list after change'),[]);
  assert(ok(await admin.storage.from('menu-pictures').list(),'Admin list after change').some(r=>r.name===name));
  const after=(await db.query("SELECT policyname,cmd,roles,qual,with_check FROM pg_policies WHERE schemaname='storage' AND tablename='objects' ORDER BY policyname")).rows;
  assert.deepEqual(after.filter(p=>p.cmd!=='SELECT'),before.filter(p=>p.cmd!=='SELECT'));
  assert.equal(after.length,before.length);
  assert.equal(after.find(p=>p.cmd==='SELECT').policyname,'Admins can list menu pictures');
  pass('Real Storage list denies anon and ordinary, retains admin listing and write policies');
  const unchanged=await fetch(publicUrl,{signal:AbortSignal.timeout(10000)});
  assert(unchanged.ok);
  assert.deepEqual(Buffer.from(await unchanged.arrayBuffer()),png);
  ok(await admin.storage.from('menu-pictures').upload('ting4-new-unique.png',png,{contentType:'image/png',upsert:false}),'New admin upload');
  assert((await ordinary.storage.from('menu-pictures').upload('ting4-denied.png',png,{contentType:'image/png',upsert:false})).error);
  assert.equal((await db.query("SELECT public FROM storage.buckets WHERE id='menu-pictures'")).rows[0].public,true);
  pass('Known public URL and unique admin upload still work; ordinary upload denied');
}
